/*
 * TestingOAuth20.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using TestingOAuth20.PCL.Controllers;
using TestingOAuth20.PCL.Http.Client;
using TestingOAuth20.PCL.Utilities;

namespace TestingOAuth20.PCL
{
    public partial class TestingOAuth20Client
    {

        /// <summary>
        /// Singleton access to HelloBinding controller
        /// </summary>
        public HelloBinding HelloBinding
        {
            get
            {
                return TestingOAuth20.PCL.Controllers.HelloBinding.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Authorization instance

        public AuthManager Auth
        {
            get { return AuthManager.Instance; }
        }

        #endregion
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public TestingOAuth20Client() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public TestingOAuth20Client(string oAuthClientId, string oAuthRedirectUri)
        {
            Configuration.OAuthClientId = oAuthClientId;
            Configuration.OAuthRedirectUri = oAuthRedirectUri;
        }
        #endregion
    }
}